/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package shoesvip.ui;
import java.awt.BorderLayout;
import java.awt.Dimension;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import java.util.List;
import java.util.Calendar;
import java.util.Date;
import static java.util.Date.from;
import shoesvip.dao.ThongKeDAO;
import shoesvip.dao.impl.ThongKeDAOImpl;
import shoesvip.entity.ThongKe;
public class BieuDoThongKe extends javax.swing.JPanel {
private javax.swing.JPanel panel_bieuDo;
    /**
     * Creates new form BieuDoThongKe
     */
    private ThongKeDAO thongKeDAO = new ThongKeDAOImpl();
    public BieuDoThongKe() {
        initComponents();
        
    }
    public static Date getStartOfDay(Date date) {
    Calendar cal = Calendar.getInstance();
    cal.setTime(date);
    cal.set(Calendar.HOUR_OF_DAY, 0);
    cal.set(Calendar.MINUTE, 0);
    cal.set(Calendar.SECOND, 0);
    cal.set(Calendar.MILLISECOND, 0);
    return cal.getTime();
}

public static Date getEndOfDay(Date date) {
    Calendar cal = Calendar.getInstance();
    cal.setTime(date);
    cal.set(Calendar.HOUR_OF_DAY, 23);
    cal.set(Calendar.MINUTE, 59);
    cal.set(Calendar.SECOND, 59);
    cal.set(Calendar.MILLISECOND, 999);
    return cal.getTime();
}

public void setDataToChart(Date from, Date to) {
    from = getStartOfDay(from);
    to = getEndOfDay(to);

    List<ThongKe> list = thongKeDAO.getThongKeTheoNamVaThang(from, to);

    // ✅ Sắp xếp theo doanh thu giảm dần
    list.sort((a, b) -> b.getTongTienSauGiam().compareTo(a.getTongTienSauGiam()));

    System.out.println("Tổng số thống kê: " + list.size());
    for (ThongKe tk : list) {
        System.out.println("Tháng " + tk.getThang() + "/" + tk.getNam() + ": " + tk.getTongTienSauGiam());
    }

    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    for (ThongKe tk : list) {
        String label = "Tháng " + tk.getThang() + "/" + tk.getNam();
        dataset.addValue(tk.getTongTienSauGiam(), "Doanh thu", label);
    }

    JFreeChart chart = ChartFactory.createBarChart(
            "Biểu đồ doanh thu theo tháng",
            "Thời gian (Tháng/Năm)",
            "Doanh thu (VNĐ)",
            dataset
    );

    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setPreferredSize(new Dimension(800, 400));
    chartPanel.setMouseWheelEnabled(true);

    panel_bieuDo.removeAll();
    panel_bieuDo.setLayout(new BorderLayout());
    panel_bieuDo.add(chartPanel, BorderLayout.CENTER);
    panel_bieuDo.validate();
    panel_bieuDo.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1143, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
