/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shoesvip.ui;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import java.awt.Image;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import shoesvip.controller.formController;
import shoesvip.entity.nhanvien;
import shoesvip.util.XAuth;
import shoesvip.util.XIcon;

/**
 *
 * @author Gigabyte
 */
public class Form extends javax.swing.JFrame implements formController {

    /**
     * Creates new form Form
     */
    public void showPanel(javax.swing.JPanel panel) {
        pnlCCenter.removeAll();                   // Xóa panel cũ
        pnlCCenter.setLayout(new java.awt.BorderLayout());
        pnlCCenter.add(panel, java.awt.BorderLayout.CENTER);
        pnlCCenter.revalidate();                 // Cập nhật lại giao diện
        pnlCCenter.repaint();
    }

    public Form() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Full màn hình
        setLocationRelativeTo(null); // Căn giữa nếu chưa maximize
        init();

        JButton[] btns = {btn_banhang, btn_hoadon, btn_khachhang, btn_nhanvien, btn_pgg, btn_sanpham, btn_thongke, btn_trangchu, btn_dangxuat};
        for (JButton btn : btns) {
            btn.setOpaque(true); // QUAN TRỌNG: cho phép vẽ nền đúng
            btn.setBorderPainted(false);
            btn.setFocusPainted(false);
            btn.setContentAreaFilled(false);
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    //   throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    //   throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                    btn.setOpaque(true);
                    btn.setBackground(new Color(255, 183, 77));

                }

                @Override
                public void mouseExited(MouseEvent e) {
                    // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                    btn.setOpaque(true);
                    btn.setBackground(new Color(14, 36, 49));

                }
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlSlide = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_trangchu = new javax.swing.JButton();
        btn_thongke = new javax.swing.JButton();
        btn_banhang = new javax.swing.JButton();
        btn_hoadon = new javax.swing.JButton();
        btn_sanpham = new javax.swing.JButton();
        btn_pgg = new javax.swing.JButton();
        btn_khachhang = new javax.swing.JButton();
        btn_nhanvien = new javax.swing.JButton();
        btn_dangxuat = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        pnlCTop = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lb_Ten = new javax.swing.JLabel();
        lb_chucvu = new javax.swing.JLabel();
        lb_anh = new javax.swing.JLabel();
        lbl_CCTOP = new javax.swing.JLabel();
        pnlCCenter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlSlide.setBackground(new java.awt.Color(14, 36, 49));
        pnlSlide.setPreferredSize(new java.awt.Dimension(180, 0));

        jLabel2.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("MENU");
        jLabel2.setMaximumSize(new java.awt.Dimension(130, 150));
        jLabel2.setPreferredSize(new java.awt.Dimension(130, 145));
        pnlSlide.add(jLabel2);

        btn_trangchu.setBackground(new java.awt.Color(14, 36, 49));
        btn_trangchu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_trangchu.setForeground(new java.awt.Color(255, 255, 255));
        btn_trangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home (1)_25x25_white.png"))); // NOI18N
        btn_trangchu.setText("  Trang Chủ");
        btn_trangchu.setBorderPainted(false);
        btn_trangchu.setContentAreaFilled(false);
        btn_trangchu.setFocusPainted(false);
        btn_trangchu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_trangchu.setPreferredSize(new java.awt.Dimension(180, 70));
        btn_trangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trangchuActionPerformed(evt);
            }
        });
        pnlSlide.add(btn_trangchu);

        btn_thongke.setBackground(new java.awt.Color(14, 36, 49));
        btn_thongke.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_thongke.setForeground(new java.awt.Color(255, 255, 255));
        btn_thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bar-chart_25x25_white.png"))); // NOI18N
        btn_thongke.setText("  Thống kê");
        btn_thongke.setBorderPainted(false);
        btn_thongke.setContentAreaFilled(false);
        btn_thongke.setFocusPainted(false);
        btn_thongke.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_thongke.setPreferredSize(new java.awt.Dimension(180, 70));
        btn_thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thongkeActionPerformed(evt);
            }
        });
        pnlSlide.add(btn_thongke);

        btn_banhang.setBackground(new java.awt.Color(14, 36, 49));
        btn_banhang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_banhang.setForeground(new java.awt.Color(255, 255, 255));
        btn_banhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shopping-cart-white-25px.png"))); // NOI18N
        btn_banhang.setText("  Bán hàng");
        btn_banhang.setBorderPainted(false);
        btn_banhang.setContentAreaFilled(false);
        btn_banhang.setFocusPainted(false);
        btn_banhang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_banhang.setPreferredSize(new java.awt.Dimension(180, 70));
        btn_banhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_banhangActionPerformed(evt);
            }
        });
        pnlSlide.add(btn_banhang);

        btn_hoadon.setBackground(new java.awt.Color(14, 36, 49));
        btn_hoadon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_hoadon.setForeground(new java.awt.Color(255, 255, 255));
        btn_hoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bill_25x25_white.png"))); // NOI18N
        btn_hoadon.setText("  Hóa Đơn");
        btn_hoadon.setBorderPainted(false);
        btn_hoadon.setContentAreaFilled(false);
        btn_hoadon.setFocusPainted(false);
        btn_hoadon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_hoadon.setPreferredSize(new java.awt.Dimension(180, 70));
        btn_hoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hoadonActionPerformed(evt);
            }
        });
        pnlSlide.add(btn_hoadon);

        btn_sanpham.setBackground(new java.awt.Color(14, 36, 49));
        btn_sanpham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_sanpham.setForeground(new java.awt.Color(255, 255, 255));
        btn_sanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shoes_25x25_white.png"))); // NOI18N
        btn_sanpham.setText("  Sản phẩm");
        btn_sanpham.setBorderPainted(false);
        btn_sanpham.setContentAreaFilled(false);
        btn_sanpham.setFocusPainted(false);
        btn_sanpham.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_sanpham.setPreferredSize(new java.awt.Dimension(180, 70));
        btn_sanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sanphamActionPerformed(evt);
            }
        });
        pnlSlide.add(btn_sanpham);

        btn_pgg.setBackground(new java.awt.Color(14, 36, 49));
        btn_pgg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_pgg.setForeground(new java.awt.Color(255, 255, 255));
        btn_pgg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/promo-code_25x25_white.png"))); // NOI18N
        btn_pgg.setText("  Phiếu giảm giá");
        btn_pgg.setBorderPainted(false);
        btn_pgg.setContentAreaFilled(false);
        btn_pgg.setFocusPainted(false);
        btn_pgg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_pgg.setPreferredSize(new java.awt.Dimension(180, 70));
        btn_pgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pggActionPerformed(evt);
            }
        });
        pnlSlide.add(btn_pgg);

        btn_khachhang.setBackground(new java.awt.Color(14, 36, 49));
        btn_khachhang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_khachhang.setForeground(new java.awt.Color(255, 255, 255));
        btn_khachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rating_25x25_white.png"))); // NOI18N
        btn_khachhang.setText("  Khách hàng");
        btn_khachhang.setBorderPainted(false);
        btn_khachhang.setContentAreaFilled(false);
        btn_khachhang.setFocusPainted(false);
        btn_khachhang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_khachhang.setPreferredSize(new java.awt.Dimension(180, 70));
        btn_khachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_khachhangActionPerformed(evt);
            }
        });
        pnlSlide.add(btn_khachhang);

        btn_nhanvien.setBackground(new java.awt.Color(14, 36, 49));
        btn_nhanvien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_nhanvien.setForeground(new java.awt.Color(255, 255, 255));
        btn_nhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/multiple-users-silhouette_25x25_white.png"))); // NOI18N
        btn_nhanvien.setText("  Nhân viên");
        btn_nhanvien.setBorderPainted(false);
        btn_nhanvien.setContentAreaFilled(false);
        btn_nhanvien.setFocusPainted(false);
        btn_nhanvien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_nhanvien.setPreferredSize(new java.awt.Dimension(180, 70));
        btn_nhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhanvienActionPerformed(evt);
            }
        });
        pnlSlide.add(btn_nhanvien);

        btn_dangxuat.setBackground(new java.awt.Color(14, 36, 49));
        btn_dangxuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_dangxuat.setForeground(new java.awt.Color(255, 255, 255));
        btn_dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout_icon_25x25_white (1).png"))); // NOI18N
        btn_dangxuat.setText("  Đăng xuất");
        btn_dangxuat.setBorderPainted(false);
        btn_dangxuat.setContentAreaFilled(false);
        btn_dangxuat.setFocusPainted(false);
        btn_dangxuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_dangxuat.setPreferredSize(new java.awt.Dimension(180, 70));
        btn_dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangxuatActionPerformed(evt);
            }
        });
        pnlSlide.add(btn_dangxuat);

        pnlRoot.add(pnlSlide, java.awt.BorderLayout.WEST);

        pnlCenter.setBackground(new java.awt.Color(243, 244, 246));
        pnlCenter.setPreferredSize(new java.awt.Dimension(2000, 918));
        pnlCenter.setLayout(new java.awt.BorderLayout());

        pnlCTop.setBackground(new java.awt.Color(204, 255, 204));
        pnlCTop.setPreferredSize(new java.awt.Dimension(0, 130));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(1, 110));

        lb_Ten.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_Ten.setText("Ten");

        lb_chucvu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_chucvu.setText("Chuc vu");

        lb_anh.setBackground(new java.awt.Color(0, 0, 0));
        lb_anh.setText("Image");

        lbl_CCTOP.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lbl_CCTOP.setText("jLabel1");

        javax.swing.GroupLayout pnlCTopLayout = new javax.swing.GroupLayout(pnlCTop);
        pnlCTop.setLayout(pnlCTopLayout);
        pnlCTopLayout.setHorizontalGroup(
            pnlCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCTopLayout.createSequentialGroup()
                .addGap(725, 725, 725)
                .addComponent(lbl_CCTOP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6838, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(pnlCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_Ten)
                    .addComponent(lb_chucvu))
                .addGap(86, 86, 86)
                .addComponent(lb_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        pnlCTopLayout.setVerticalGroup(
            pnlCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_Ten)
                .addGap(28, 28, 28)
                .addComponent(lb_chucvu)
                .addGap(29, 29, 29))
            .addGroup(pnlCTopLayout.createSequentialGroup()
                .addGroup(pnlCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCTopLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lb_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCTopLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lbl_CCTOP)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnlCenter.add(pnlCTop, java.awt.BorderLayout.PAGE_START);

        pnlCCenter.setBackground(new java.awt.Color(255, 255, 255));
        pnlCCenter.setPreferredSize(new java.awt.Dimension(0, 100));

        javax.swing.GroupLayout pnlCCenterLayout = new javax.swing.GroupLayout(pnlCCenter);
        pnlCCenter.setLayout(pnlCCenterLayout);
        pnlCCenterLayout.setHorizontalGroup(
            pnlCCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlCCenterLayout.setVerticalGroup(
            pnlCCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );

        pnlCenter.add(pnlCCenter, java.awt.BorderLayout.CENTER);

        pnlRoot.add(pnlCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_trangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trangchuActionPerformed
        // TODO add your handling code here:
        this.showHomeJPanel(this);

    }//GEN-LAST:event_btn_trangchuActionPerformed

    private void btn_banhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_banhangActionPerformed
        // TODO add your handling code here:
        this.showBanHangJPanel(this);

    }//GEN-LAST:event_btn_banhangActionPerformed

    private void btn_hoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hoadonActionPerformed
        // TODO add your handling code here:

        this.showHoaDonJPanel(this);

    }//GEN-LAST:event_btn_hoadonActionPerformed

    private void btn_khachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_khachhangActionPerformed
        // TODO add your handling code here:
        this.showKhachhangJPanel(this);

    }//GEN-LAST:event_btn_khachhangActionPerformed

    private void btn_pggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pggActionPerformed
        // TODO add your handling code here:
        this.showpggJpanel(this);

    }//GEN-LAST:event_btn_pggActionPerformed

    private void btn_sanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sanphamActionPerformed
        // TODO add your handling code here:
        this.showsanphamJpanel(this);

    }//GEN-LAST:event_btn_sanphamActionPerformed

    private void btn_nhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhanvienActionPerformed
        // TODO add your handling code here:
        this.shownhanvienJpanel(this);

    }//GEN-LAST:event_btn_nhanvienActionPerformed

    private void btn_thongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thongkeActionPerformed
        // TODO add your handling code here:
        this.showthongkeJpanel(this);

    }//GEN-LAST:event_btn_thongkeActionPerformed

    private void btn_dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangxuatActionPerformed
        // TODO add your handling code here:

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn đăng xuất?",
                "Đăng xuất", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose(); // Đóng form hiện tại (giao diện chính)

            // Mở lại giao diện đăng nhập (JDialog)
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    LoginFame dialog = new LoginFame();
                    dialog.setLocationRelativeTo(null);
                    dialog.setVisible(true);
                }
            });
        }
    }//GEN-LAST:event_btn_dangxuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_banhang;
    private javax.swing.JButton btn_dangxuat;
    private javax.swing.JButton btn_hoadon;
    private javax.swing.JButton btn_khachhang;
    private javax.swing.JButton btn_nhanvien;
    private javax.swing.JButton btn_pgg;
    private javax.swing.JButton btn_sanpham;
    private javax.swing.JButton btn_thongke;
    private javax.swing.JButton btn_trangchu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_Ten;
    private javax.swing.JLabel lb_anh;
    private javax.swing.JLabel lb_chucvu;
    private javax.swing.JLabel lbl_CCTOP;
    private javax.swing.JPanel pnlCCenter;
    private javax.swing.JPanel pnlCTop;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSlide;
    // End of variables declaration//GEN-END:variables
    @Override
    public void init() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

        this.showHomeJPanel(this);
        if (XAuth.user != null) {
            phanQuyen(XAuth.user);
            initNhanVienInfo();
        }

    }

    @Override
    public void showHomeJPanel(JFrame frame) {
        //   throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        lbl_CCTOP.setText("Trang chủ");
        homePanel panel = new homePanel();
        showPanel(panel);
    }

    @Override
    public void showBanHangJPanel(JFrame frame) {
        //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        banhangJPanel panel = new banhangJPanel();
        showPanel(panel);
        lbl_CCTOP.setText("Bán hàng");
    }

    @Override
    public void showHoaDonJPanel(JFrame frame) {
        //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        hoadonJPanel panel = new hoadonJPanel(this);
        showPanel(panel);
        lbl_CCTOP.setText("Quản lý hóa đơn");
    }

    @Override
    public void showKhachhangJPanel(JFrame frame) {
        // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        KhachHangJPanel panel = new KhachHangJPanel();
        showPanel(panel);
        lbl_CCTOP.setText("Quản lý khách hàng");
    }

    @Override
    public void showpggJpanel(JFrame frame) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        pggJPanel panel = new pggJPanel();
        showPanel(panel);
        lbl_CCTOP.setText("Quản lý phiếu giảm giá");
    }

    @Override
    public void shownhanvienJpanel(JFrame frame) {
        // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        NhanVienJPanel panel = new NhanVienJPanel();
        showPanel(panel);
        lbl_CCTOP.setText("Quản lý nhân viên");
    }

    @Override
    public void showsanphamJpanel(JFrame frame) {
        //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        sanphamJPanel panel = new sanphamJPanel();
        showPanel(panel);
        lbl_CCTOP.setText("Quản lý sản phẩm");
    }

    @Override
    public void showthongkeJpanel(JFrame frame) {
        //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        thongkeJPanel panel = new thongkeJPanel();
        showPanel(panel);
        lbl_CCTOP.setText("Quản lý thống kê");
    }

    private void phanQuyen(nhanvien nv) {
        int idVaiTro = nv.getIdvaitro();
        if (idVaiTro == 2) { // Quản lý
            btn_banhang.setVisible(true);
            btn_hoadon.setVisible(true);
            btn_khachhang.setVisible(true);
            btn_nhanvien.setVisible(true);
            btn_pgg.setVisible(true);
            btn_sanpham.setVisible(true);
            btn_thongke.setVisible(true);
        } else if (idVaiTro == 1) { // Nhân viên
            btn_banhang.setVisible(true);
            btn_hoadon.setVisible(true);
            btn_khachhang.setVisible(true);
            btn_nhanvien.setVisible(false);
            btn_pgg.setVisible(false);
            btn_sanpham.setVisible(true);
            btn_thongke.setVisible(false);
        }

        btn_dangxuat.setVisible(true);

        // Gán hiển thị thông tin
        String chucVu = (idVaiTro == 2) ? "Quản lý" : "Nhân viên";
        lb_Ten.setText("Xin chào: " + nv.getHovaten());
        lb_chucvu.setText("Chức vụ: " + chucVu);
    }

    public void initNhanVienInfo() {
        nhanvien nv = XAuth.user;
        System.out.println("XAuth.user: " + nv);

        if (nv == null) {
            return;
        }

        String photo = nv.getAnh();
        String fullName = nv.getHovaten();
        int idVaiTro = nv.getIdvaitro();

        System.out.println("Họ tên: " + fullName);
        System.out.println("Ảnh: " + photo);
        System.out.println("Vai trò: " + idVaiTro);

        if (photo == null || photo.trim().isEmpty()) {
            if (lb_anh != null) {
                XIcon.setIcon(lb_anh, "/icons/profile.png");
            }
        } else {
            if (lb_anh != null) {
                String path = "/icons/" + photo;
                System.out.println("Đang set ảnh: " + path);
                XIcon.setIcon(lb_anh, path);
            }
        }

        if (lb_Ten != null) {
            lb_Ten.setText(fullName);
        }
        if (lb_chucvu != null) {
            String roleText = (idVaiTro == 2) ? "Quản lý" : "Nhân viên";
            lb_chucvu.setText(roleText);
        }
    }
}
