 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package shoesvip.ui;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import java.awt.image.BufferedImage;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.util.List;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import shoesvip.dao.impl.chatlieuDAOImpl;
import shoesvip.dao.impl.daygiayDAOImpl;
import shoesvip.dao.impl.gioitinhDAOImpl;
import shoesvip.dao.impl.kichcoDAOImpl;
import shoesvip.dao.impl.kieudangDAOImpl;
import shoesvip.dao.impl.loaidegiayDAOImpl;
import shoesvip.dao.impl.loaigiayDAOImpl;
import shoesvip.dao.impl.mausacDAOImpl;
import shoesvip.dao.impl.sanphamchitietDAOImpl;
import shoesvip.dao.impl.sanphamDAOImpl;
import shoesvip.dao.impl.thuonghieuDAOImpl;
import shoesvip.dao.impl.xuatxuDAOImpl;
import shoesvip.entity.chatlieu;
import shoesvip.entity.daygiay;
import shoesvip.entity.gioitinh;
import shoesvip.entity.kichco;
import shoesvip.entity.kieudang;
import shoesvip.entity.loaidegiay;
import shoesvip.entity.loaigiay;
import shoesvip.entity.mausac;
import shoesvip.entity.sanphamchitiet;
import shoesvip.entity.thuonghieu;
import shoesvip.entity.xuatxu;
import shoesvip.util.XDialog;
import shoesvip.dao.chatlieuDAO;
import shoesvip.dao.daygiayDAO;
import shoesvip.dao.gioitinhDAO;
import shoesvip.dao.kichcoDAO;
import shoesvip.dao.kieudangDAO;
import shoesvip.dao.loaidegiayDAO;
import shoesvip.dao.loaigiayDAO;
import shoesvip.dao.mausacDAO;
import shoesvip.dao.sanphamchitietDAO;
import shoesvip.dao.sanphamDAO;
import shoesvip.dao.thuonghieuDAO;
import shoesvip.dao.xuatxuDAO;

/**
 *
 * @author Admin
 */
public class HienthithongtinchitietsanphamJDialog extends javax.swing.JDialog {

    /**
     * Creates new form HienthithongtinchitietsanphamJDialog
     */
    private DefaultComboBoxModel cbo = new DefaultComboBoxModel();
      List<sanphamchitiet> lstChiTiets = List.of();
    sanphamchitietDAO SPCT = new sanphamchitietDAOImpl();
     List<shoesvip.entity.sanpham> lstSanPhams = List.of();
    sanphamDAO SPCN = new sanphamDAOImpl();
    List<thuonghieu> lstThuongHieus = List.of();
    thuonghieuDAO THCN = new thuonghieuDAOImpl();
    List<loaigiay> lstLoaiGiays = List.of();
    loaigiayDAO LDCN = new loaigiayDAOImpl();
    List<kichco> lstKichCos = List.of();
    kichcoDAO KCCN = new kichcoDAOImpl();
    List<gioitinh> lstGioiTinhs = List.of();
    gioitinhDAO GTCN = new gioitinhDAOImpl();
    List<mausac> lstMauSacs = List.of();
    mausacDAO MSCN = new mausacDAOImpl();
    List<xuatxu> lstXuatXus = List.of();
    xuatxuDAO XXCN = new xuatxuDAOImpl();
    List<chatlieu> lstChatLieus = List.of();
    chatlieuDAO CLCN = new chatlieuDAOImpl();
    List<loaidegiay> lstLoaiDeGiays = List.of();
    loaidegiayDAO LDGCN = new loaidegiayDAOImpl();
    List<daygiay> lstDayGiays = List.of();
    daygiayDAO DGCN = new daygiayDAOImpl();
    List<kieudang> lstKieuDangs = List.of();
    kieudangDAO KDCN = new kieudangDAOImpl();
    sanphamJPanel s = new sanphamJPanel();
      private int id;
     private String ma;
     // Chỉ cho phép nhập số 0-9
    
    public HienthithongtinchitietsanphamJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Thông Tin Sản Phẩm Chi Tiết");
        setLocationRelativeTo(null);
         this.fillComBoBox();
        this.fillComBoBox1();
        this.fillComBoBox2();
        this.fillComBoBox3();
        this.fillComBoBox4();
        this.fillComBoBox5();
        this.fillComBoBox6();
        this.fillComBoBox7();
        this.fillComBoBox8();
        this.fillComBoBox9();
        this.fillComBoBox10();
        // kiểm tra ô nhập input
       ((AbstractDocument) txt_ctgiaban.getDocument()).setDocumentFilter(new NumericFilter());
        ((AbstractDocument) txt_ctsoluong.getDocument()).setDocumentFilter(new NumericFilter());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbo_ctten = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbo_ctthuonghieu = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbo_ctxuatxu = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbo_ctloaigiay = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbo_ctgioitinh = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbo_ctmausac = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbo_ctkichco = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbo_ctchatlieu = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbo_ctloaidegiay = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbo_ctdaygiay = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cbo_ctkieudang = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_ctgiaban = new javax.swing.JTextField();
        txt_ctsoluong = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        panel_quetmaQR = new javax.swing.JPanel();
        lbl_QR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Thông Tin Chi Tiết Sản Phẩm");

        jLabel2.setText("Tên Sản Phẩm");

        jLabel3.setText("Xuất Xứ");

        jLabel4.setText("Loại Giày ");

        jLabel5.setText("Thương Hiệu");

        jLabel6.setText("Giới Tính");

        jLabel7.setText("Màu Sắc");

        jLabel8.setText("Kích Cỡ");

        jLabel9.setText("Chất Liệu");

        jLabel10.setText("Loại Đế Giày");

        cbo_ctloaidegiay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_ctloaidegiayActionPerformed(evt);
            }
        });

        jLabel11.setText("Dây Giày");

        cbo_ctdaygiay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_ctdaygiayActionPerformed(evt);
            }
        });

        jLabel12.setText("Kiểu Dáng");

        cbo_ctkieudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_ctkieudangActionPerformed(evt);
            }
        });

        jLabel13.setText("Giá Bán");

        jLabel14.setText("Số Lượng");

        txt_ctsoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ctsoluongActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(102, 102, 102));
        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_update.setText("Cập Nhật");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        panel_quetmaQR.setBackground(new java.awt.Color(255, 255, 255));
        panel_quetmaQR.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_QR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_QR.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout panel_quetmaQRLayout = new javax.swing.GroupLayout(panel_quetmaQR);
        panel_quetmaQR.setLayout(panel_quetmaQRLayout);
        panel_quetmaQRLayout.setHorizontalGroup(
            panel_quetmaQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_quetmaQRLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_QR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        panel_quetmaQRLayout.setVerticalGroup(
            panel_quetmaQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_quetmaQRLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_QR, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_ctxuatxu, 0, 248, Short.MAX_VALUE)
                            .addComponent(cbo_ctthuonghieu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbo_ctloaigiay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbo_ctten, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_quetmaQR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_ctgioitinh, 0, 230, Short.MAX_VALUE)
                            .addComponent(cbo_ctmausac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbo_ctkichco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbo_ctchatlieu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_ctsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)))
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbo_ctloaidegiay, 0, 182, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addComponent(cbo_ctdaygiay, 0, 182, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(cbo_ctkieudang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_ctgiaban)
                    .addComponent(jLabel10)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(255, 255, 255))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbo_ctchatlieu, cbo_ctdaygiay, cbo_ctgioitinh, cbo_ctkichco, cbo_ctloaidegiay, cbo_ctloaigiay, cbo_ctmausac, cbo_ctten, cbo_ctthuonghieu, cbo_ctxuatxu});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(cbo_ctmausac, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel8)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_ctchatlieu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_ctgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addComponent(cbo_ctkichco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_ctsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_ctloaidegiay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_ctdaygiay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_ctkieudang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ctgiaban, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_ctten, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(cbo_ctthuonghieu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_ctxuatxu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel5)))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_ctloaigiay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(panel_quetmaQR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbo_ctchatlieu, cbo_ctdaygiay, cbo_ctgioitinh, cbo_ctkichco, cbo_ctloaidegiay, cbo_ctloaigiay, cbo_ctmausac, cbo_ctten, cbo_ctthuonghieu, cbo_ctxuatxu});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_ctloaidegiayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_ctloaidegiayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_ctloaidegiayActionPerformed

    private void cbo_ctdaygiayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_ctdaygiayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_ctdaygiayActionPerformed

    private void cbo_ctkieudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_ctkieudangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_ctkieudangActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        if (!XDialog.confirm("Bạn có Muốn Cập Nhật Không")) {
            return;
        }
        sanphamchitiet sp = this.GetForm(id);
        if (sp==null) {
            return;
        }
        SPCT.update(sp);
        SPCN.findAll();
//         SPCN.updateSoLuongTon(sp.getIdsanpham());
          XDialog.alert("Cập Nhật Thành Công");
    }//GEN-LAST:event_btn_updateActionPerformed

    private void txt_ctsoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ctsoluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ctsoluongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HienthithongtinchitietsanphamJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HienthithongtinchitietsanphamJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HienthithongtinchitietsanphamJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HienthithongtinchitietsanphamJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HienthithongtinchitietsanphamJDialog dialog = new HienthithongtinchitietsanphamJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
      void fillComBoBox(){
     
     cbo=(DefaultComboBoxModel) cbo_ctchatlieu.getModel();
     cbo_ctchatlieu.removeAllItems();
     lstChatLieus=CLCN.findAll();
     for (chatlieu t : lstChatLieus) {
         cbo_ctchatlieu.addItem(t.getTenchatlieu());
        ;
     }
 }
      void fillComBoBox1(){
     cbo=(DefaultComboBoxModel) cbo_ctdaygiay.getModel();
     cbo_ctdaygiay.removeAllItems();
     lstDayGiays=DGCN.findAll();
     for (daygiay d : lstDayGiays) {
         cbo_ctdaygiay.addItem(d.getTendaygiay());
//             AutoCompleteDecorator.decorate(cbo_ctdaygiay);
     }
      }
      void fillComBoBox2(){
     cbo=(DefaultComboBoxModel) cbo_ctloaidegiay.getModel();
     cbo_ctloaidegiay.removeAllItems();
    lstLoaiDeGiays=LDGCN.findAll();
     for (loaidegiay t : lstLoaiDeGiays) {
         cbo_ctloaidegiay.addItem(t.getTenloaidegiay());
//             AutoCompleteDecorator.decorate(cbo_degiay);
     }
      }
      void fillComBoBox3(){
     cbo=(DefaultComboBoxModel) cbo_ctgioitinh.getModel();
     cbo_ctgioitinh.removeAllItems();
     lstGioiTinhs=GTCN.findAll();
     for (gioitinh t : lstGioiTinhs) {
         cbo_ctgioitinh.addItem(t.getTengioitinh());
//             AutoCompleteDecorator.decorate(cbo_gioitinh);
     }
      }
void fillComBoBox4(){
     cbo=(DefaultComboBoxModel) cbo_ctkichco.getModel();
     cbo_ctkichco.removeAllItems();
     lstKichCos=KCCN.findAll();
     for (kichco t : lstKichCos) {
         cbo_ctkichco.addItem(t.getTenkichco());
//             AutoCompleteDecorator.decorate(cbo_kichco);
     }
      }
     void fillComBoBox5(){
     cbo=(DefaultComboBoxModel) cbo_ctkieudang.getModel();
     cbo_ctkieudang.removeAllItems();
     lstKieuDangs=KDCN.findAll();
     for (kieudang t : lstKieuDangs) {
         cbo_ctkieudang.addItem(t.getTenkieudang());
//             AutoCompleteDecorator.decorate(cbo_kieudang);
     }
      }
     void fillComBoBox6(){
     cbo=(DefaultComboBoxModel) cbo_ctloaigiay.getModel();
     cbo_ctloaigiay.removeAllItems();
     lstLoaiGiays=LDCN.findAll();
     for (loaigiay t : lstLoaiGiays) {
         cbo_ctloaigiay.addItem(t.getTenloaigiay());
//             AutoCompleteDecorator.decorate(cbo_loaigiay);
     }
     }
     void fillComBoBox7(){
     cbo=(DefaultComboBoxModel) cbo_ctmausac.getModel();
     cbo_ctmausac.removeAllItems();
     lstMauSacs=MSCN.findAll();
     for (mausac t : lstMauSacs) {
         cbo_ctmausac.addItem(t.getTenmausac());
//             AutoCompleteDecorator.decorate(cbo_mausac);
     }
     }
     void fillComBoBox8(){
     cbo=(DefaultComboBoxModel) cbo_ctten.getModel();
     cbo_ctten.removeAllItems();
     lstSanPhams=SPCN.findAll();
     for (shoesvip.entity.sanpham t : lstSanPhams) {
         cbo_ctten.addItem(t.getTensanpham());
//             AutoCompleteDecorator.decorate(cbo_tensp);
     }
     }
     void fillComBoBox9(){
     cbo=(DefaultComboBoxModel) cbo_ctthuonghieu.getModel();
     cbo_ctthuonghieu.removeAllItems();
     lstThuongHieus=THCN.findAll();
     for (thuonghieu t : lstThuongHieus) {
         cbo_ctthuonghieu.addItem(t.getTenthuonghieu());
//             AutoCompleteDecorator.decorate(cbo_thuonghieu);
     }
     }
     void fillComBoBox10(){
     cbo=(DefaultComboBoxModel) cbo_ctxuatxu.getModel();
     cbo_ctxuatxu.removeAllItems();
     lstXuatXus=XXCN.findAll();
     for (xuatxu t : lstXuatXus) {
         cbo_ctxuatxu.addItem(t.getTenxuatxu());
//             AutoCompleteDecorator.decorate(cbo_xuatxu);
     }
     }
   
   public void setform(int id, String ma,String tenSp,String tenTH,String tenXX,String loaigiay,String gioitinh,String mausac,String kichco,String chatlieu,int soluong,String loaidegiay,String daygiay,String kieudang, BigDecimal giaban){
       this.id = id;
       this.ma= ma;
        cbo_ctchatlieu.setSelectedItem(chatlieu);
       cbo_ctdaygiay.setSelectedItem(daygiay);
       cbo_ctgioitinh.setSelectedItem(gioitinh);
       cbo_ctkichco.setSelectedItem(kichco);
       cbo_ctkieudang.setSelectedItem(kieudang);
       cbo_ctloaidegiay.setSelectedItem(loaidegiay);
       cbo_ctloaigiay.setSelectedItem(loaigiay);
       cbo_ctmausac.setSelectedItem(mausac);
       cbo_ctten.setSelectedItem(tenSp);
       cbo_ctthuonghieu.setSelectedItem(tenTH);
       cbo_ctxuatxu.setSelectedItem(tenXX);
       txt_ctgiaban.setText(formatCurrency(giaban));
       txt_ctsoluong.setText(String.valueOf(soluong));
       this.showQRCodeForSPCT(ma);
     }
   
     
    public  sanphamchitiet GetForm(int id){
         if (txt_ctgiaban.getText().trim().isEmpty()) {
             XDialog.alert("Giá bán Bị TRống");
             txt_ctgiaban.requestFocus();
             return null;
         }
         if (txt_ctsoluong.getText().trim().isEmpty()) {
             XDialog.alert("Số Lượng Bị TRống");
             txt_ctsoluong.requestFocus();
             return null;
         }
         BigDecimal gban = parseCurrency(txt_ctgiaban.getText());
         int solg = Integer.parseInt(txt_ctsoluong.getText());
             if (gban.compareTo(BigDecimal.ZERO)<=0) {
                 XDialog.alert("Vui lòng nhập đúng giá(giá phải lớn hơn không)");
                 return null;
             }
             if (solg<=0) {
                  XDialog.alert("Vui lòng nhập đúng số lượng(số lượng phải lớn hơn hoặc bằng không)");
                 return null;
             }
       
        
         
         shoesvip.entity.sanpham s = (shoesvip.entity.sanpham) SPCN.findByTen1("%"+cbo_ctten.getSelectedItem().toString()+"%");
         int idSP=s.getIdsanpham();
         thuonghieu t = THCN.findByTen(cbo_ctthuonghieu.getSelectedItem().toString());
         int idTH=t.getIdthuonghieu();
         xuatxu x = XXCN.findByTen(cbo_ctxuatxu.getSelectedItem().toString());
         int idXX= x.getIdxuatxu();
         loaigiay l = LDCN.findByTen(cbo_ctloaigiay.getSelectedItem().toString());
         int idloaigiay=l.getIdloaigiay();
         gioitinh g = GTCN.findByTen("%"+cbo_ctgioitinh.getSelectedItem().toString()+"%");
          int idGT= g.getIdgioitinh();
          mausac m = MSCN.findByTen("%"+cbo_ctmausac.getSelectedItem().toString()+"%");
          int idMS = m.getIdmausac();
          kichco k = KCCN.findByTen("%"+cbo_ctkichco.getSelectedItem().toString()+"%");
          int idKC = k.getIdkichco();
          chatlieu c = CLCN.findByTen("%"+cbo_ctchatlieu.getSelectedItem().toString()+"%");
          int idCL = c.getIdchatlieu();
          loaidegiay d = LDGCN.findByTen("%"+cbo_ctloaidegiay.getSelectedItem().toString()+"%");
          int idLDG = d.getIdloaidegiay();
          kieudang kd = KDCN.findByTen("%"+cbo_ctkieudang.getSelectedItem().toString()+"%");
          int idKD = kd.getIdkieudang();
          int idDG = DGCN.findByTen("%"+cbo_ctdaygiay.getSelectedItem().toString()+"%").getIddaygiay();
           int idSPCT = id;
           return  new sanphamchitiet(idSPCT, idSP, idTH, idloaigiay, idKC, idGT, idMS, idXX, idCL, idLDG, idDG, idKD, gban, solg,true);
    }
       public String maSPCT() {
        String prefix = "SPCT-";
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder sb = new StringBuilder();

        Random random = new Random();
        for (int i = 0; i < 6; i++) {
            int index1 = random.nextInt(chars.length());
            sb.append(chars.charAt(index1));
        }

        return prefix + sb.toString();
    }
       private void showQRCodeForSPCT(String maSPCT) {
    try {
        // Tạo QR code trực tiếp (không lưu file)
        BitMatrix matrix = new MultiFormatWriter()
                .encode(maSPCT, BarcodeFormat.QR_CODE, 200, 200);
        BufferedImage qrImage = MatrixToImageWriter.toBufferedImage(matrix);
        lbl_QR.setIcon(new ImageIcon(qrImage));
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cbo_ctchatlieu;
    private javax.swing.JComboBox<String> cbo_ctdaygiay;
    private javax.swing.JComboBox<String> cbo_ctgioitinh;
    private javax.swing.JComboBox<String> cbo_ctkichco;
    private javax.swing.JComboBox<String> cbo_ctkieudang;
    private javax.swing.JComboBox<String> cbo_ctloaidegiay;
    private javax.swing.JComboBox<String> cbo_ctloaigiay;
    private javax.swing.JComboBox<String> cbo_ctmausac;
    private javax.swing.JComboBox<String> cbo_ctten;
    private javax.swing.JComboBox<String> cbo_ctthuonghieu;
    private javax.swing.JComboBox<String> cbo_ctxuatxu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_QR;
    private javax.swing.JPanel panel_quetmaQR;
    private javax.swing.JTextField txt_ctgiaban;
    private javax.swing.JTextField txt_ctsoluong;
    // End of variables declaration//GEN-END:variables
class NumericFilter extends DocumentFilter {
    @Override
    public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr)
            throws BadLocationException {
        if (string != null) {
            string = string.replaceAll("[^0-9]", ""); // Loại bỏ ký tự không phải số
            super.insertString(fb, offset, string, attr);
        }
    }

    @Override
    public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
            throws BadLocationException {
        if (text != null) {
            text = text.replaceAll("[^0-9]", ""); // Loại bỏ ký tự không phải số
            super.replace(fb, offset, length, text, attrs);
        }
    }
}
public String formatCurrency(BigDecimal value) {
    DecimalFormatSymbols symbols = new DecimalFormatSymbols();
    symbols.setGroupingSeparator('.');
    DecimalFormat df = new DecimalFormat("#,###", symbols);
    df.setMaximumFractionDigits(0); // Không lấy phần thập phân
    df.setParseBigDecimal(true);
    return df.format(value) + " đ";
}
public BigDecimal parseCurrency(String text) {
    try {
        DecimalFormatSymbols symbols = new DecimalFormatSymbols();
        symbols.setGroupingSeparator('.');
        DecimalFormat df = new DecimalFormat("#,###", symbols);
        df.setParseBigDecimal(true);

        text = text.replace("đ", "").replace("Đ", "").trim();
        return (BigDecimal) df.parse(text);
    } catch (ParseException e) {
        // Nếu parse lỗi thì trả về 0
        return BigDecimal.ZERO;
    }
}
}
