/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package shoesvip.ui;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.jdesktop.swingx.prompt.PromptSupport;
import shoesvip.dao.GiaoDichDAO;
import shoesvip.dao.impl.khachhangDAOImpl;
import shoesvip.dao.khachhangDAO;
import shoesvip.entity.diachikhachhang;
import shoesvip.entity.khachhang;
import shoesvip.controller.khachhangController;
import shoesvip.dao.impl.diachikhachhangDAOImpl;
import shoesvip.dao.diachikhachhangDAO;
import shoesvip.dao.hoadonDAO;
import shoesvip.dao.impl.GiaoDichDAOImpl;
import shoesvip.dao.impl.hoadonDAOImpl;
import shoesvip.entity.GiaoDich;
import shoesvip.entity.hoadon;
import shoesvip.util.XDate;
import shoesvip.util.XDialog;
import java.math.BigDecimal;

/**
 *
 * @author Ba Nguyen
 */
public final class KhachHangJPanel extends javax.swing.JPanel implements khachhangController {

    /**
     * Creates new form KhachHangJPanel
     */
    public KhachHangJPanel() {

        initComponents();
        PromptSupport.setPrompt("Tìm kiếm tên khách hàng ...", txt_timkiem);
        PromptSupport.setPrompt("Tìm kiếm theo mã giao dịch ...", txt_timkiem2);
        fillToTable();
        loadDiaChiToComboBox();
        txt_makh.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_makh = new javax.swing.JTextField();
        txt_ten = new javax.swing.JTextField();
        txt_ngaysinh = new javax.swing.JTextField();
        txt_gioitinh = new javax.swing.JLabel();
        rdo_nam = new javax.swing.JRadioButton();
        rdo_nu = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_lammoi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbo_diachi = new javax.swing.JComboBox<>();
        btn_xuat = new javax.swing.JButton();
        btn_import = new javax.swing.JButton();
        btn_diachi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tab = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txt_timkiem = new javax.swing.JTextField();
        btn_timkiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_thongtinkhachhang = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_timkiem2 = new javax.swing.JTextField();
        btn_timkiem2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_lichsugiaodich = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        jLabel2.setText("Mã KH:");

        jLabel3.setText("Họ Và Tên:");

        jLabel4.setText("Ngày Sinh");

        txt_makh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_makhActionPerformed(evt);
            }
        });

        txt_gioitinh.setText("Giới Tính");

        buttonGroup1.add(rdo_nam);
        rdo_nam.setText("Nam");
        rdo_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_namActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo_nu);
        rdo_nu.setText("Nữ");
        rdo_nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_nuActionPerformed(evt);
            }
        });

        jLabel6.setText("SĐT:");

        jLabel7.setText("Email:");

        btn_add.setBackground(new java.awt.Color(102, 102, 102));
        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-removebg-preview.png"))); // NOI18N
        btn_add.setText("Thêm");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_sua.setBackground(new java.awt.Color(102, 102, 102));
        btn_sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tools.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(102, 102, 102));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btn_delete.setText("Xóa");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_lammoi.setBackground(new java.awt.Color(102, 102, 102));
        btn_lammoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_lammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/load-removebg-preview (1).png"))); // NOI18N
        btn_lammoi.setText("Làm Mới");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });

        jLabel5.setText("Địa Chỉ");

        cbo_diachi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_xuat.setBackground(new java.awt.Color(153, 153, 153));
        btn_xuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/file (1).png"))); // NOI18N
        btn_xuat.setText("XuấtExel");
        btn_xuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xuatActionPerformed(evt);
            }
        });

        btn_import.setBackground(new java.awt.Color(102, 102, 102));
        btn_import.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_import.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow.png"))); // NOI18N
        btn_import.setText(" ImportExel");
        btn_import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_importActionPerformed(evt);
            }
        });

        btn_diachi.setBackground(new java.awt.Color(102, 102, 102));
        btn_diachi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-removebg-preview.png"))); // NOI18N
        btn_diachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_diachiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_makh, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                            .addComponent(txt_ten))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(txt_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbo_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_add)
                                .addGap(176, 176, 176)
                                .addComponent(btn_sua)
                                .addGap(181, 181, 181)
                                .addComponent(btn_delete)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(206, 206, 206)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_lammoi)
                                .addGap(68, 68, 68)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_xuat)
                                    .addComponent(rdo_nam))
                                .addGap(82, 82, 82)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdo_nu)
                                        .addGap(174, 174, 174))
                                    .addComponent(btn_import, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(134, 134, 134))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_makh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdo_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdo_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbo_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_diachi))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_add)
                    .addComponent(btn_sua)
                    .addComponent(btn_delete)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_xuat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_import, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_lammoi)))
                .addGap(30, 30, 30))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Thiết lập Thông Tin Khách Hàng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tab.setBackground(new java.awt.Color(255, 255, 255));
        tab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btn_timkiem.setBackground(new java.awt.Color(102, 102, 102));
        btn_timkiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btn_timkiem.setText("Tìm Kiếm ");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_timkiem)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_timkiem)
                    .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tbl_thongtinkhachhang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        tbl_thongtinkhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã KH", "Họ và Tên", "Ngày Sinh", "SĐT", "Email", "Giới Tính", "Địa Chỉ"
            }
        ));
        tbl_thongtinkhachhang.setRowHeight(52);
        tbl_thongtinkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_thongtinkhachhangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_thongtinkhachhangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_thongtinkhachhangMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_thongtinkhachhang);
        if (tbl_thongtinkhachhang.getColumnModel().getColumnCount() > 0) {
            tbl_thongtinkhachhang.getColumnModel().getColumn(0).setMinWidth(100);
            tbl_thongtinkhachhang.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbl_thongtinkhachhang.getColumnModel().getColumn(0).setMaxWidth(100);
            tbl_thongtinkhachhang.getColumnModel().getColumn(1).setMinWidth(100);
            tbl_thongtinkhachhang.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbl_thongtinkhachhang.getColumnModel().getColumn(1).setMaxWidth(100);
            tbl_thongtinkhachhang.getColumnModel().getColumn(4).setMinWidth(150);
            tbl_thongtinkhachhang.getColumnModel().getColumn(4).setPreferredWidth(150);
            tbl_thongtinkhachhang.getColumnModel().getColumn(4).setMaxWidth(150);
            tbl_thongtinkhachhang.getColumnModel().getColumn(6).setMinWidth(100);
            tbl_thongtinkhachhang.getColumnModel().getColumn(6).setPreferredWidth(100);
            tbl_thongtinkhachhang.getColumnModel().getColumn(6).setMaxWidth(100);
            tbl_thongtinkhachhang.getColumnModel().getColumn(7).setMinWidth(400);
            tbl_thongtinkhachhang.getColumnModel().getColumn(7).setPreferredWidth(400);
            tbl_thongtinkhachhang.getColumnModel().getColumn(7).setMaxWidth(400);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1642, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tab.addTab("Thông tin khách hàng", jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btn_timkiem2.setBackground(new java.awt.Color(255, 183, 77));
        btn_timkiem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_timkiem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btn_timkiem2.setText("Tìm Kiếm");
        btn_timkiem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiem2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_timkiem2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_timkiem2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_timkiem2)
                    .addComponent(btn_timkiem2))
                .addGap(25, 25, 25))
        );

        tbl_lichsugiaodich.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        tbl_lichsugiaodich.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã KH", "Mã HĐ", "Tên KH", "SĐT", "Địa Chỉ", "Ngày Giao Dịch", "Tổng Tiền", "Trạng Thái"
            }
        ));
        tbl_lichsugiaodich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_lichsugiaodichMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_lichsugiaodich);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1639, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tab.addTab("Lịch sử giao dịch", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 1694, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:                                      
        try {
            if (!validateFormKhachHang()) {
                return;
            }
            String maKH = maKhachHangNgauNhien();

            txt_makh.repaint(); // ép giao diện cập nhật lại
            txt_makh.revalidate();

            int confirm = JOptionPane.showConfirmDialog(this,
                    "Bạn có chắc chắn muốn thêm khách hàng này?",
                    "Xác nhận thêm",
                    JOptionPane.YES_NO_OPTION);
            if (confirm != JOptionPane.YES_OPTION) {
                return; // Không thêm nếu người dùng chọn "No"
            }

            khachhang kh = readForm();
            kh.setMakhachhang(maKH);
            if (kh == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin khách hàng.");
                return;
            }

            // ======================== CHECK TRÙNG ========================
            List<khachhang> listKH = khDAO.findAll();
            boolean isDuplicate = listKH.stream().anyMatch(e
                    -> e.getSodienthoai().equalsIgnoreCase(kh.getSodienthoai())
                    || e.getEmail().equalsIgnoreCase(kh.getEmail())
            );
            if (isDuplicate) {
                JOptionPane.showMessageDialog(this, "Khách hàng đã tồn tại (trùng SĐT hoặc Email)!");
                return;
            }
            // ============================================================
            khDAO.create(kh);
            fillToTable();
            clearForm();
            JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm khách hàng!\n" + e.getMessage());
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        int row = tbl_thongtinkhachhang.getSelectedRow();
        txt_makh.setText("");
        if (row < 0) {
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn ẩn khách hàng này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            khachhang kh = listKH.get(row); // dùng list thay vì lấy từ table
            khDAO.delete(kh.getIdkhachhang());
            fillToTable();
            clearForm();
        }

    }//GEN-LAST:event_btn_deleteActionPerformed

    private void rdo_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_namActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        String keyword = txt_timkiem.getText().trim(); // txtTim là ô nhập tìm kiếm
        if (keyword.isEmpty()) {
            fillToTable(); // hiển thị lại toàn bộ nếu rỗng
            return;
        }

        try {
            List<khachhang> list = khDAO.findByTen(keyword);
            DefaultTableModel model = (DefaultTableModel) tbl_thongtinkhachhang.getModel();
            model.setRowCount(0); // clear table
            int stt = 0;
            for (khachhang kh : list) {
                model.addRow(new Object[]{
                    ++stt,
                    kh.getMakhachhang(),
                    kh.getHovaten(),
                    kh.getNgaysinh(),
                    kh.getSodienthoai(),
                    kh.getEmail(),
                    kh.getGioitinh() == null ? "" : (kh.getGioitinh() ? "Nam" : "Nữ"),
                    kh.getIddiachi() == null ? "" : dckhDAO.findById(kh.getIddiachi()).getTinhthanh(),});
            }

            if (list.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng nào!");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm khách hàng!");
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        int row = tbl_thongtinkhachhang.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khách hàng cần cập nhật.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn cập nhật thông tin khách hàng này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            if (!validateFormKhachHang()) {
                return;
            }
            khachhang kh = listKH.get(row); // Danh sách này bạn đã fill từ khDAO.findAll()

            if (kh == null) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng.");
                return;
            }

            khachhang khMoi = readForm();
            khMoi.setIdkhachhang(kh.getIdkhachhang()); // Giữ nguyên ID cũ
            khDAO.update(khMoi); // Cập nhật thông tin

            fillToTable();
            clearForm();

            JOptionPane.showMessageDialog(this, "Cập nhật khách hàng thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật khách hàng!");
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        // TODO add your handling code here:
        try {
            fillToTable();
            txt_makh.setText("");// Tự load lại từ DB
            tbl_thongtinkhachhang.clearSelection(); // Bỏ chọn dòng
            clearForm();                      // Xoá dữ liệu ở form nếu có
            JOptionPane.showMessageDialog(this, "Đã làm mới!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi làm mới dữ liệu!");
        }
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void tbl_lichsugiaodichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_lichsugiaodichMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tbl_lichsugiaodichMouseClicked

    private void rdo_nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_nuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_nuActionPerformed

    private void tbl_thongtinkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_thongtinkhachhangMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tbl_thongtinkhachhangMouseClicked

    private void btn_timkiem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiem2ActionPerformed
        // TODO add your handling code here:
        String keyword = txt_timkiem2.getText().trim().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) tbl_lichsugiaodich.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ
        List<GiaoDich> danhSach = gdDAO.findAll(); // hoặc findByKhachHang(maKH)
        int stt = 1;

        for (GiaoDich gd : danhSach) {
            String maHD = gd.getMaHoaDon();
            if (maHD != null && maHD.toLowerCase().contains(keyword)) {
                model.addRow(new Object[]{
                    stt++,
                    gd.getMaKhachHang(),
                    gd.getMaHoaDon(),
                    gd.getHovaten(),
                    gd.getSoDienThoai(),
                    gd.getTinhthanh(),
                    XDate.format(gd.getNgayxuathoadon(), XDate.PATTERN_FULL_rever), // Có thể format lại nếu cần
                    formatCurrency(gd.getTongtiensaugiam()), // Có thể format 2.160.000 đ
                    (gd.getTrangThai() == 0 ? "Đã thanh toán" : gd.getTrangThai() == gd.getTrangThai() ? "Chưa thanh toán" : "Đã hủy")
                });
            }
        }
    }//GEN-LAST:event_btn_timkiem2ActionPerformed

    private void tbl_thongtinkhachhangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_thongtinkhachhangMousePressed
        // TODO add your handling code here:
        int row = tbl_thongtinkhachhang.getSelectedRow();
        if (row == -1) {
            return;
        }
        if (evt.getClickCount() == 2) {
            // Double click: chuyển tab, gọi edit
            tab.setSelectedIndex(1);
            edit();
        } else if (evt.getClickCount() == 1) {
            // Single click: load dữ liệu vào các ô text
            edit1();
        }
    }//GEN-LAST:event_tbl_thongtinkhachhangMousePressed

    private void btn_xuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xuatActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Chọn nơi lưu Excel");

        if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            if (!file.getName().endsWith(".xlsx")) {
                file = new File(file.getAbsolutePath() + ".xlsx");
            }
            if (tab.getSelectedIndex() == 0) {
                listKH = khDAO.findAll();
                exportKhachHangToExcel(listKH, file);
            } else {
                exportlsdg(file);
            }
        }
    }//GEN-LAST:event_btn_xuatActionPerformed

    private void btn_importActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_importActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            importKhachHangFromExcel(file);
        }
    }//GEN-LAST:event_btn_importActionPerformed

    private void btn_diachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_diachiActionPerformed
        // TODO add your handling code here:
        themdiachinhanhJDialog dialog = new themdiachinhanhJDialog(null, true);
        dialog.setLocationRelativeTo(this); // Đặt vị trí trước khi hiển thị
        dialog.setVisible(true);

        if (dialog.isSubmitted()) {
            loadDiaChiToComboBox();
            JOptionPane.showMessageDialog(this, "Đã thêm địa chỉ mới thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Địa chỉ chưa được thêm.");
        }
    }//GEN-LAST:event_btn_diachiActionPerformed

    private void txt_makhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_makhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_makhActionPerformed

    private void tbl_thongtinkhachhangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_thongtinkhachhangMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_thongtinkhachhangMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_diachi;
    private javax.swing.JButton btn_import;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_timkiem2;
    private javax.swing.JButton btn_xuat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbo_diachi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdo_nam;
    private javax.swing.JRadioButton rdo_nu;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tbl_lichsugiaodich;
    private javax.swing.JTable tbl_thongtinkhachhang;
    private javax.swing.JTextField txt_email;
    private javax.swing.JLabel txt_gioitinh;
    private javax.swing.JTextField txt_makh;
    private javax.swing.JTextField txt_ngaysinh;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_timkiem;
    private javax.swing.JTextField txt_timkiem2;
    // End of variables declaration//GEN-END:variables
DefaultTableModel moda = new DefaultTableModel();
    khachhangDAO khDAO = new khachhangDAOImpl();
    List<khachhang> listKH = List.of();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    diachikhachhangDAO dckhDAO = new diachikhachhangDAOImpl();
    List<diachikhachhang> listdckh1 = List.of();
    hoadonDAO hoadonDAO = new hoadonDAOImpl();

    @Override
    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_thongtinkhachhang.getModel();
        model.setRowCount(0); // Xóa trắng

        listKH = khDAO.findAll(); // Lấy lại dữ liệu từ DB
        int stt = 0;
        for (khachhang kh : listKH) {
            Integer id = kh.getIddiachi();
            model.addRow(new Object[]{
                ++stt,
                kh.getMakhachhang(),
                kh.getHovaten(),
                XDate.format(kh.getNgaysinh(), XDate.PATTERN_SHORT_DAY),
                kh.getSodienthoai(),
                kh.getEmail(),
                kh.getGioitinh() == null ? "" : (kh.getGioitinh() ? "Nam" : "Nữ"),
                id != null ? (dckhDAO.findById(kh.getIddiachi()).getDiachicuthe() + ", " + dckhDAO.findById(kh.getIddiachi()).getPhuongxa() + ", " + dckhDAO.findById(kh.getIddiachi()).getQuanhuyen() + ", " + dckhDAO.findById(kh.getIddiachi()).getTinhthanh()) : ""
            }
            );
        }
    }

    private void loadTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_thongtinkhachhang.getModel();
        model.setRowCount(0);
        int stt = 0;
        List<khachhang> list = khDAO.findAll();
        for (khachhang kh : list) {
            Integer id = kh.getIddiachi();
            model.addRow(new Object[]{
                ++stt,
                kh.getMakhachhang(),
                kh.getHovaten(),
                XDate.format(kh.getNgaysinh(), XDate.PATTERN_SHORT_DAY),
                kh.getSodienthoai(),
                kh.getEmail(),
                kh.getGioitinh() == null ? "" : (kh.getGioitinh() ? "Nam" : "Nữ"),
                id != null ? (dckhDAO.findById(kh.getIddiachi()).getDiachicuthe() + ", " + dckhDAO.findById(kh.getIddiachi()).getPhuongxa() + ", " + dckhDAO.findById(kh.getIddiachi()).getQuanhuyen() + ", " + dckhDAO.findById(kh.getIddiachi()).getTinhthanh()) : ""
            });
        }
    }

    private khachhang readForm() {
        khachhang kh = new khachhang();
        kh.setIddiachi(listdckh1.get(cbo_diachi.getSelectedIndex()).getIddiachi());
        kh.setMakhachhang(txt_makh.getText().trim());
        kh.setHovaten(txt_ten.getText().trim());
        kh.setSodienthoai(txt_sdt.getText().trim());
        kh.setEmail(txt_email.getText().trim());
        kh.setGioitinh(rdo_nam.isSelected()); // true nếu Nam, false nếu Nữ

        String ngaySinhStr = txt_ngaysinh.getText().trim();
        Date ngaySinh = parseDate(ngaySinhStr);
        kh.setNgaysinh(ngaySinh);
        // Gán ngày thêm và người thêm mặc định
        kh.setTrangthaian(true);
        return kh;
    }

    private Date parseDate(String dateStr) {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            sdf.setLenient(false); // tránh chấp nhận ngày sai như 32/01/2024
            return sdf.parse(dateStr);
        } catch (ParseException e) {
            return null;
        }
    }

    @Override
    public void clearForm() {
        txt_makh.setText(maKhachHangNgauNhien());
        txt_makh.setText("");
        txt_ten.setText("");
        txt_sdt.setText("");
        txt_email.setText("");
        rdo_nam.setSelected(true); // Mặc định chọn Nam
        txt_ngaysinh.setText("");  // Nếu dùng JDateChooser thì: dateChooser_ngaySinh.setDate(null);
        cbo_diachi.setSelectedIndex(-1);
    }

    private void loadDiaChiToComboBox() {
        cbo_diachi.removeAllItems();
        cbo_diachi.addItem("");
        listdckh1 = dckhDAO.findAll();
        for (diachikhachhang dc : listdckh1) {
            String diaChiStr = dc.getDiachicuthe() + ", " + dc.getPhuongxa() + ", " + dc.getQuanhuyen() + ", " + dc.getTinhthanh();
            cbo_diachi.addItem(diaChiStr);
        }
    }

    public String maKhachHangNgauNhien() {
        String prefix = "KH-";
        String chars = "QWERTYUIOPASDFGHJKLZXCVNM0123456789";
        StringBuilder sb = new StringBuilder();
        Random random = new Random();

        for (int i = 0; i < 6; i++) {
            int index = random.nextInt(chars.length());
            sb.append(chars.charAt(index));
        }

        return prefix + sb.toString();
    }

    public String maDCKhachHangNgauNhien() {
        String prefix = "DCKH-";
        String chars = "QWERTYUIOPASDFGHJKLZXCVNM0123456789";
        StringBuilder sb = new StringBuilder();
        Random random = new Random();

        for (int i = 0; i < 6; i++) {
            int index = random.nextInt(chars.length());
            sb.append(chars.charAt(index));
        }

        return prefix + sb.toString();
    }

    private boolean validateFormKhachHang() {

        if (txt_ten.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập họ và tên.");
            txt_ten.requestFocus();
            return false;
        }
        String sdt = txt_sdt.getText().trim();
        if (sdt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại.");
            txt_sdt.requestFocus();
            return false;
        }
        if (!sdt.matches("^0\\d{9}$")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ. Ví dụ: 0901234567");
            txt_sdt.requestFocus();
            return false;
        }

        String email = txt_email.getText().trim();
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email không được để trống");
            txt_email.requestFocus();
            return false;
        }
        if (!email.isEmpty() && !email.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) {
            JOptionPane.showMessageDialog(this, "Email không đúng định dạng.");
            txt_email.requestFocus();
            return false;
        }
        String ngaySinhStr = txt_ngaysinh.getText().trim();
        if (ngaySinhStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày sinh.");
            txt_ngaysinh.requestFocus();
            return false;
        }

        Date ngaySinh = parseDate(ngaySinhStr);
        if (ngaySinh == null) {
            JOptionPane.showMessageDialog(this, "Ngày sinh không đúng định dạng (dd/MM/yyyy).");
            txt_ngaysinh.requestFocus();
            return false;
        }
        if (ngaySinh.after(new Date())) {
            JOptionPane.showMessageDialog(this, "Ngày sinh không được lớn hơn ngày hiện tại.");
            txt_ngaysinh.requestFocus();
            return false;
        }
        if (cbo_diachi.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn địa chỉ.");
            cbo_diachi.requestFocus();
            return false;
        }

        return true;
    }

    void exportlsdg(File file) {
        try (Workbook workbook = new XSSFWorkbook()) {
            Sheet sheet = workbook.createSheet("Lịch sử giao dịch");
            Row headerRow = sheet.createRow(0);
            int rowNum = 1;
            int stt = 1;

            NumberFormat nf = NumberFormat.getInstance(new Locale("vi", "VN"));
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

            String[] headers = {
                "STT", "Mã KH", "Mã hóa đơn", "Họ tên", "SĐT", "Địa chỉ", "Ngày giao dịch",
                "Tổng tiền", "Trạng thái"
            };
            for (int i = 0; i < headers.length; i++) {
                headerRow.createCell(i).setCellValue(headers[i]);
            }

            // Lấy danh sách giao dịch của khách hàng đang chọn
            listgd = gdDAO.findByKhachHangId(listKH.get(tbl_thongtinkhachhang.getSelectedRow()).getIdkhachhang());

            for (GiaoDich x : listgd) {
                Row row = sheet.createRow(rowNum++);
                row.createCell(0).setCellValue(stt++);
                row.createCell(1).setCellValue(x.getMaKhachHang());
                row.createCell(2).setCellValue(x.getMaHoaDon());
                row.createCell(3).setCellValue(x.getHovaten());
                row.createCell(4).setCellValue(x.getSoDienThoai());
                row.createCell(5).setCellValue(x.getTinhthanh());
                row.createCell(6).setCellValue(XDate.format(x.getNgayxuathoadon(), XDate.PATTERN_FULL_rever));
                row.createCell(7).setCellValue(formatCurrency(x.getTongtiensaugiam()));
                row.createCell(8).setCellValue(
                        x.getTrangThai() == 0 ? "Đã thanh toán"
                        : x.getTrangThai() == 1 ? "Chưa thanh toán" : "Đã hủy"
                );
            }

            // Ghi file Excel
            try (FileOutputStream fos = new FileOutputStream(file)) {
                workbook.write(fos);
            }

            JOptionPane.showMessageDialog(null, "Xuất Excel thành công!");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi khi xuất Excel!");
        }
    }

    public void exportKhachHangToExcel(List<khachhang> listKH, File file) {
        // 0 = khách hàng, 1 = lịch sử giao dịch

        try (Workbook workbook = new XSSFWorkbook()) {
            Sheet sheet;
            Row headerRow;
            int rowNum = 1;
            int stt = 1;

            NumberFormat nf = NumberFormat.getInstance(new Locale("vi", "VN"));
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

            // ======= DANH SÁCH KHÁCH HÀNG (KHÔNG PHÂN TÍCH HÓA ĐƠN) =======
            sheet = workbook.createSheet("Danh sách khách hàng");
            String[] headers = {"STT", "Mã KH", "Họ tên", "Ngày sinh", "SĐT", "Email", "Giới tính", "Địa chỉ"};
            headerRow = sheet.createRow(0);
            for (int i = 0; i < headers.length; i++) {
                headerRow.createCell(i).setCellValue(headers[i]);
            }

            for (khachhang kh : listKH) {
                diachikhachhang d = dckhDAO.findById(kh.getIddiachi());
                String diachiStr = (d != null)
                        ? d.getDiachicuthe() + ", " + d.getPhuongxa() + ", " + d.getQuanhuyen() + ", " + d.getTinhthanh()
                        : "";

                Row row = sheet.createRow(rowNum++);
                row.createCell(0).setCellValue(stt++);
                row.createCell(1).setCellValue(kh.getMakhachhang());
                row.createCell(2).setCellValue(kh.getHovaten());
                row.createCell(3).setCellValue(kh.getNgaysinh() != null ? sdf.format(kh.getNgaysinh()) : "");
                row.createCell(4).setCellValue(kh.getSodienthoai());
                row.createCell(5).setCellValue(kh.getEmail());
                row.createCell(6).setCellValue(kh.getGioitinh() ? "Nam" : kh.getGioitinh() == false ? "Nữ" : "");
                row.createCell(7).setCellValue(diachiStr);
            }

            // Ghi file Excel
            try (FileOutputStream fos = new FileOutputStream(file)) {
                workbook.write(fos);
            }

            JOptionPane.showMessageDialog(null, "Xuất Excel thành công!");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi khi xuất Excel!");
        }

    }

    public void importKhachHangFromExcel(File file) {

        try (FileInputStream fis = new FileInputStream(file); XSSFWorkbook workbook = new XSSFWorkbook(fis)) {
            XSSFSheet sheet = workbook.getSheetAt(0);
            DefaultTableModel model = (DefaultTableModel) tbl_thongtinkhachhang.getModel();
            model.setRowCount(0); // Xóa dữ liệu cũ
            DataFormatter formatter = new DataFormatter();

            // Lấy toàn bộ địa chỉ từ DB để map
            List<diachikhachhang> listDiaChi = dckhDAO.findAll();

            int count = 0;
            for (int i = 1; i <= sheet.getLastRowNum(); i++) {
                Row row = sheet.getRow(i);
                if (row != null) {
                    try {

                        String tenKH = formatter.formatCellValue(row.getCell(0));
                        String ngaySinhStr = formatter.formatCellValue(row.getCell(1));
                        String sdt = formatter.formatCellValue(row.getCell(2));
                        String email = formatter.formatCellValue(row.getCell(3));
                        String gioiTinhStr = formatter.formatCellValue(row.getCell(4));
                        String diaChiExcel = formatter.formatCellValue(row.getCell(5));

                        // Parse ngày sinh
                        Date ngaySinh = ngaySinhStr.isEmpty() ? null : sdf.parse(ngaySinhStr);
                        boolean gioiTinh = gioiTinhStr.equalsIgnoreCase("Nam");

                        // Map địa chỉ từ Excel sang id
                        int idDiaChi = 0;
                        for (diachikhachhang dc : listDiaChi) {
                            String fullDC = dc.getDiachicuthe() + ", " + dc.getPhuongxa() + ", " + dc.getQuanhuyen() + ", " + dc.getTinhthanh();
                            if (fullDC.equalsIgnoreCase(diaChiExcel.trim())) {
                                idDiaChi = dc.getIddiachi(); // hoặc dc.getIddiachi()
                                break;
                            }
                        }
                        String[] parts = diaChiExcel.split(",");
                        if (idDiaChi == 0) {
                            dckhDAO.create(new diachikhachhang(maDCKhachHangNgauNhien(), parts[0].trim(), parts[1].trim(), parts[2].trim(), parts[3].trim(), null, null, null, null, XDate.now(), null, null, true));

                        }
                        listDiaChi = dckhDAO.findAll();
                        idDiaChi = listDiaChi.get(listDiaChi.size() - 1).getIddiachi();
                        // Tạo khách hàng
                        khachhang kh = new khachhang();
                        kh.setMakhachhang(maKhachHangNgauNhien());
                        kh.setHovaten(tenKH);
                        kh.setNgaysinh(ngaySinh);
                        kh.setSodienthoai(sdt);
                        kh.setEmail(email);
                        kh.setGioitinh(gioiTinh);
                        kh.setIddiachi(idDiaChi);

                        // Lưu DB
                        khDAO.create(kh);

                        // Hiển thị bảng
                        loadTable();
                        count++;
                    } catch (Exception rowEx) {
                        System.err.println("Lỗi dòng " + (i + 1) + ": " + rowEx.getMessage());
                    }
                }
            }

            JOptionPane.showMessageDialog(null, "Đã import và lưu " + count + " khách hàng vào hệ thống!");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi khi đọc file Excel: " + ex.getMessage());
        }

    }

    @Override
    public void filltoall(List<khachhang> a) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void timKiem() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void them() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void sua() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void xoa() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void open() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setForm(khachhang entity) {
        // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        txt_makh.setText(entity.getMakhachhang());
        txt_ten.setText(entity.getHovaten());
        txt_ngaysinh.setText(XDate.format(entity.getNgaysinh(), XDate.PATTERN_SHORT_DAY));
        txt_sdt.setText(entity.getSodienthoai());
        txt_email.setText(entity.getEmail());

        if (entity.getGioitinh() == null) {
            rdo_nam.setSelected(false);
            rdo_nu.setSelected(false);

        } else if (entity.getGioitinh() == false) {
            rdo_nu.setSelected(true);
        } else {
            rdo_nam.setSelected(true);
        }
        if (entity.getIddiachi() != null) {
            cbo_diachi.setSelectedItem((dckhDAO.findById(entity.getIddiachi()).getDiachicuthe() + ", " + dckhDAO.findById(entity.getIddiachi()).getPhuongxa() + ", " + dckhDAO.findById(entity.getIddiachi()).getQuanhuyen() + ", " + dckhDAO.findById(entity.getIddiachi()).getTinhthanh()));
        } else {
            cbo_diachi.setSelectedIndex(0);
        }
    }

    @Override
    public khachhang getForm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private List<GiaoDich> listgd;
    private GiaoDichDAO gdDAO = new GiaoDichDAOImpl();

    void edit1() {
        khachhang kh = listKH.get(tbl_thongtinkhachhang.getSelectedRow());
        setForm(kh);
    }

    @Override
    public void edit() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        moda = (DefaultTableModel) tbl_lichsugiaodich.getModel();
        moda.setRowCount(0);
        listgd = gdDAO.findByKhachHangId(listKH.get(tbl_thongtinkhachhang.getSelectedRow()).getIdkhachhang());
        moda.setRowCount(0);
        int stt = 0;
        for (GiaoDich x : listgd) {
            moda.addRow(new Object[]{
                ++stt,
                x.getMaKhachHang(),
                x.getMaHoaDon(),
                x.getHovaten(),
                x.getSoDienThoai(),
                x.getTinhthanh(),
                XDate.format(x.getNgayxuathoadon(), XDate.PATTERN_FULL_rever),
                formatCurrency(x.getTongtiensaugiam()),
                (x.getTrangThai() == 0 ? "Đã thanh toán" : x.getTrangThai() == x.getTrangThai() ? "Chưa thanh toán" : "Đã hủy")
            }
            );
        }

    }

    @Override
    public void create() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void update() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void delete() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void clear() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setEditable(boolean editable) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void checkAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void uncheckAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void deleteCheckedItems() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveFirst() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void movePrevious() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveNext() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveLast() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveTo(int rowIndex) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public String formatCurrency(BigDecimal value) {
        DecimalFormatSymbols symbols = new DecimalFormatSymbols();
        symbols.setGroupingSeparator('.');
        DecimalFormat df = new DecimalFormat("#,###", symbols);
        df.setMaximumFractionDigits(0); // Không lấy phần thập phân
        df.setParseBigDecimal(true);
        return df.format(value) + " đ";
    }

    @Override
    public void locTheoNgay() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
