/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package shoesvip.ui;

import java.awt.event.ActionEvent;
import java.util.List;
import java.util.Random;
import shoesvip.dao.impl.chatlieuDAOImpl;
import shoesvip.dao.impl.daygiayDAOImpl;
import shoesvip.dao.impl.gioitinhDAOImpl;
import shoesvip.dao.impl.kichcoDAOImpl;
import shoesvip.dao.impl.kieudangDAOImpl;
import shoesvip.dao.impl.loaidegiayDAOImpl;
import shoesvip.dao.impl.loaigiayDAOImpl;
import shoesvip.dao.impl.mausacDAOImpl;
import shoesvip.dao.impl.thuonghieuDAOImpl;
import shoesvip.dao.impl.xuatxuDAOImpl;
import shoesvip.entity.chatlieu;
import shoesvip.entity.daygiay;
import shoesvip.entity.gioitinh;
import shoesvip.entity.kichco;
import shoesvip.entity.kieudang;
import shoesvip.entity.loaidegiay;
import shoesvip.entity.loaigiay;
import shoesvip.entity.mausac;
import shoesvip.entity.thuonghieu;
import shoesvip.entity.xuatxu;
import shoesvip.util.XDialog;
import shoesvip.dao.chatlieuDAO;
import shoesvip.dao.daygiayDAO;
import shoesvip.dao.gioitinhDAO;
import shoesvip.dao.kichcoDAO;
import shoesvip.dao.kieudangDAO;
import shoesvip.dao.loaidegiayDAO;
import shoesvip.dao.loaigiayDAO;
import shoesvip.dao.mausacDAO;
import shoesvip.dao.thuonghieuDAO;
import shoesvip.dao.xuatxuDAO;

/**
 *
 * @author Admin
 */
public class themthuoctinhnhanhJDialog extends javax.swing.JDialog {

    List<thuonghieu> lstThuongHieus = List.of();
    thuonghieuDAO THCN = new thuonghieuDAOImpl();
    List<loaigiay> lstLoaiGiays = List.of();
    loaigiayDAO LDCN = new loaigiayDAOImpl();
    List<kichco> lstKichCos = List.of();
    kichcoDAO KCCN = new kichcoDAOImpl();
    List<gioitinh> lstGioiTinhs = List.of();
    gioitinhDAO GTCN = new gioitinhDAOImpl();
    List<mausac> lstMauSacs = List.of();
    mausacDAO MSCN = new mausacDAOImpl();
    List<xuatxu> lstXuatXus = List.of();
    xuatxuDAO XXCN = new xuatxuDAOImpl();
    List<chatlieu> lstChatLieus = List.of();
    chatlieuDAO CLCN = new chatlieuDAOImpl();
    List<loaidegiay> lstLoaiDeGiays = List.of();
    loaidegiayDAO LDGCN = new loaidegiayDAOImpl();
    List<daygiay> lstDayGiays = List.of();
    daygiayDAO DGCN = new daygiayDAOImpl();
    List<kieudang> lstKieuDangs = List.of();
    kieudangDAO KDCN = new kieudangDAOImpl();
    sanphamJPanel s = new sanphamJPanel();
    String loaithuoctinh;

    public themthuoctinhnhanhJDialog(java.awt.Frame parent, boolean modal, String loaithuoctinh) {
        super(parent, modal);
        this.loaithuoctinh = loaithuoctinh;
        initComponents();
        setTitle("Thêm " + this.loaithuoctinh);
        setLocationRelativeTo(null);
        txt_mathuoctinh.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_mathuoctinh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        btn_themthuoctinh = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mã Thuộc Tính");

        txt_mathuoctinh.setBackground(new java.awt.Color(242, 242, 242));
        txt_mathuoctinh.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Tên Thuộc Tính");

        txt_name.setBackground(new java.awt.Color(242, 242, 242));
        txt_name.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_themthuoctinh.setText("Thêm");
        btn_themthuoctinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themthuoctinhActionPerformed(evt);
            }
        });

        btn_huy.setText("Hủy");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txt_mathuoctinh, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_huy)
                .addGap(18, 18, 18)
                .addComponent(btn_themthuoctinh)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_mathuoctinh, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_themthuoctinh)
                    .addComponent(btn_huy))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themthuoctinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themthuoctinhActionPerformed
        // TODO add your handling code here:
        switch (loaithuoctinh) {
            case "thuonghieu":
                createTH();
                break;
            case "chatlieu":
                createchatLieu();
                break;
            case "daygiay":
                createDayGiay();
                break;
            case "kichco":
                createKichCo();
                break;
            case "kieudang":
                createKieuDang();
                break;
            case "loaidegiay":
                createLoaiDeGiay();
                break;
            case "loaigiay":
                createLoaiGiay();
                break;
            case "mausac":
                createMauSac();
                break;
            case "xuatxu":
                createXuatXu();
                break;
            default:
                XDialog.alert("Không xác định được loại thuộc tính");
                break;
        }
        this.dispose(); // Đóng dialog sau khi thêm thành công

    }//GEN-LAST:event_btn_themthuoctinhActionPerformed

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_btn_huyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(themthuoctinhnhanhJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(themthuoctinhnhanhJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(themthuoctinhnhanhJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(themthuoctinhnhanhJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        String loaithuoctinh = "xuatxu";
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                themthuoctinhnhanhJDialog dialog = new themthuoctinhnhanhJDialog(new javax.swing.JFrame(), true, loaithuoctinh);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public thuonghieu getformTHuongHieu() {
        thuonghieu h = new thuonghieu();

        h.setMathuonghieu(this.maTH());
        h.setTenthuonghieu(txt_name.getText().trim());
        return h;
    }

    public chatlieu getformCHatLieu() {
        chatlieu h = new chatlieu();

        h.setMachatlieu(this.maCL());
        h.setTenchatlieu(txt_name.getText().trim());
        return h;
    }

    public daygiay getformDayGiay() {
        daygiay h = new daygiay();

        h.setMadaygiay(this.maDG());
        h.setTendaygiay(txt_name.getText().trim());
        return h;
    }

    public kichco getformKichCo() {
        kichco h = new kichco();

        h.setMakichco(this.maKC());
        h.setTenkichco(txt_name.getText().trim());
        return h;
    }

    public kieudang getformKieuDang() {
        kieudang h = new kieudang();

        h.setMakieudang(this.maKD());
        h.setTenkieudang(txt_name.getText().trim());
        return h;
    }

    public loaidegiay getformLoaiDeGiay() {
        loaidegiay h = new loaidegiay();

        h.setMaloaidegiay(this.maLD());
        h.setTenloaidegiay(txt_name.getText().trim());
        return h;
    }

    public loaigiay getformLOaiGiay() {
        loaigiay h = new loaigiay();

        h.setMaloaigiay(this.maLDG());
        h.setTenloaigiay(txt_name.getText());
        return h;
    }

    public mausac getformMauSac() {
        mausac h = new mausac();

        h.setMamausac(this.maMS());
        h.setTenmausac(txt_name.getText().trim());
        return h;
    }

    public xuatxu getformXuatXu() {
        xuatxu x = new xuatxu();

        x.setMaxuatxu(this.maXX());
        x.setTenxuatxu(txt_name.getText().trim());
        return x;
    }
    // ramdom mã sản phẩm chi tiết

    public String maTH() {
        String prefix = "TH-";
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder sb = new StringBuilder();

        Random random = new Random();
        for (int i = 0; i < 6; i++) {
            int index1 = random.nextInt(chars.length());
            sb.append(chars.charAt(index1));
        }

        return prefix + sb.toString();
    }

    public String maCL() {
        String prefix = "CL-";
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder sb = new StringBuilder();

        Random random = new Random();
        for (int i = 0; i < 6; i++) {
            int index1 = random.nextInt(chars.length());
            sb.append(chars.charAt(index1));
        }

        return prefix + sb.toString();
    }

    public String maDG() {
        String prefix = "DG-";
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder sb = new StringBuilder();

        Random random = new Random();
        for (int i = 0; i < 6; i++) {
            int index1 = random.nextInt(chars.length());
            sb.append(chars.charAt(index1));
        }

        return prefix + sb.toString();
    }

    public String maKD() {
        String prefix = "KD-";
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder sb = new StringBuilder();

        Random random = new Random();
        for (int i = 0; i < 6; i++) {
            int index1 = random.nextInt(chars.length());
            sb.append(chars.charAt(index1));
        }

        return prefix + sb.toString();
    }

    public String maKC() {
        String prefix = "KC-";
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder sb = new StringBuilder();

        Random random = new Random();
        for (int i = 0; i < 6; i++) {
            int index1 = random.nextInt(chars.length());
            sb.append(chars.charAt(index1));
        }

        return prefix + sb.toString();
    }

    public String maLDG() {
        String prefix = "LDG-";
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder sb = new StringBuilder();

        Random random = new Random();
        for (int i = 0; i < 6; i++) {
            int index1 = random.nextInt(chars.length());
            sb.append(chars.charAt(index1));
        }

        return prefix + sb.toString();
    }

    public String maLD() {
        String prefix = "LD-";
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder sb = new StringBuilder();

        Random random = new Random();
        for (int i = 0; i < 6; i++) {
            int index1 = random.nextInt(chars.length());
            sb.append(chars.charAt(index1));
        }

        return prefix + sb.toString();
    }

    public String maMS() {
        String prefix = "MS-";
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder sb = new StringBuilder();

        Random random = new Random();
        for (int i = 0; i < 6; i++) {
            int index1 = random.nextInt(chars.length());
            sb.append(chars.charAt(index1));
        }

        return prefix + sb.toString();
    }

    public void createTH() {
        if (!XDialog.confirm("Bạn có muốn thêm không")) {
            return;
        }
        thuonghieu h = this.getformTHuongHieu();
        if (txt_name.getText().trim().isEmpty()) {
            txt_name.requestFocus();
            XDialog.alert("Tên Bị Trống");
            return;
        }
         // biểu thức chính quy
         String regex = "^[\\p{L}\\s]+$";
         if (!txt_name.getText().matches(regex)) {
            XDialog.alert("Tên kiểu dáng phải là chữ và không có kí tự đặc biệt");
            return ;
        }
          String input =txt_name.getText().trim().replaceAll("\\s+", "");// replaceAll dùng để gộp nhiều khoảng trắng thành 0
       
        for (thuonghieu k : THCN.findAll()) {
              String db= k.getTenthuonghieu().trim().replaceAll("\\s+", "");
            if (input.equalsIgnoreCase(db)) {
                XDialog.alert("Trùng Tên Thương Hiệu");
                txt_name.setText("");
                return;
            }
        }
        THCN.create(h);
        XDialog.alert("Thêm Thành Công");
    }

    public void createchatLieu() {
        if (!XDialog.confirm("Bạn có muốn thêm không")) {
            return;
        }
        
        if (txt_name.getText().trim().isEmpty()) {
            txt_name.requestFocus();
            XDialog.alert("Tên Bị Trống");
            return;
        }
         // biểu thức chính quy
         String regex = "^[\\p{L}\\s]+$";
         if (!txt_name.getText().matches(regex)) {
            XDialog.alert("Tên kiểu dáng phải là chữ và không có kí tự đặc biệt");
            return ;
        }
         String input =txt_name.getText().trim().replaceAll("\\s+", "");// replaceAll dùng để gộp nhiều khoảng trắng thành 0
       
        for (chatlieu k : CLCN.findAll()) {
               String db= k.getTenchatlieu().trim().replaceAll("\\s+", "");
            if (input.equalsIgnoreCase(db)) {
                XDialog.alert("Trùng Tên Chất Liệu");
                txt_name.setText("");
                return;
            }
        }
        chatlieu h = this.getformCHatLieu();
        CLCN.create(h);
        XDialog.alert("Thêm Thành Công");
    }

    public void createDayGiay() {
        if (!XDialog.confirm("Bạn có muốn thêm không")) {
            return;
        }
        
        if (txt_name.getText().trim().isEmpty()) {
            txt_name.requestFocus();
            XDialog.alert("Tên Bị Trống");
            return;
        }
         // biểu thức chính quy
         String regex = "^[\\p{L}\\s]+$";
         if (!txt_name.getText().matches(regex)) {
            XDialog.alert("Tên kiểu dáng phải là chữ và không có kí tự đặc biệt");
            return ;
        }
         String input =txt_name.getText().trim().replaceAll("\\s+", "");// replaceAll dùng để gộp nhiều khoảng trắng thành 0
       
        for (daygiay k : DGCN.findAll()) {
               String db= k.getTendaygiay().trim().replaceAll("\\s+", "");
            if (input.equalsIgnoreCase(db)) {
                XDialog.alert("Trùng Tên Dây Giày");
                txt_name.setText("");
                return;
            }
        }
        daygiay h = this.getformDayGiay();
        DGCN.create(h);
        XDialog.alert("Thêm Thành Công");
    }

    public void createKichCo() {
        if (!XDialog.confirm("Bạn có muốn thêm không")) {
            return;
        }
        
        if (txt_name.getText().trim().isEmpty()) {
            txt_name.requestFocus();
            XDialog.alert("Tên Bị Trống");
            return;
        }
          String input =txt_name.getText().trim().replaceAll("\\s+", "");// replaceAll dùng để gộp nhiều khoảng trắng thành 0
       

        for (kichco k : KCCN.findAll()) {
            String db= k.getTenkichco().trim().replaceAll("\\s+", "");
            if (input.equalsIgnoreCase(db)) {
                XDialog.alert("Trùng Tên size");
                txt_name.setText("");
                return;
            }
        }
        int SIZE_MIN = 36;
            int SIZE_MAX = 43;
             
            int sizeValue;
            // Kiểm tra dữ liệu có phải số không
            try {
                sizeValue = Integer.parseInt(txt_name.getText().trim().replaceAll("\\s+", ""));
            } catch (NumberFormatException e) {
                XDialog.alert("Tên size phải là số (ví dụ: 36, 37...)");
                txt_name.setText("");
                return ;
            }
            
            if (sizeValue < SIZE_MIN || sizeValue > SIZE_MAX) {
                XDialog.alert("Size không hợp lệ Size chỉ cho phép từ" + SIZE_MIN + "đến" + SIZE_MAX);
                 txt_name.setText("");
                return ;
            }
      
        kichco h = this.getformKichCo();
        KCCN.create(h);
        XDialog.alert("Thêm Thành Công");
    }

    public void createKieuDang() {
        if (!XDialog.confirm("Bạn có muốn thêm không")) {
            return;
        }
        
        if (txt_name.getText().trim().isEmpty()) {
            txt_name.requestFocus();
            XDialog.alert("Tên Bị Trống");
            return;
        }
         // biểu thức chính quy
         String regex = "^[\\p{L}\\s]+$";
         if (!txt_name.getText().matches(regex)) {
            XDialog.alert("Tên kiểu dáng phải là chữ và không có kí tự đặc biệt");
             txt_name.setText("");
            return ;
        }
        String input =txt_name.getText().trim().replaceAll("\\s+", "");// replaceAll dùng để gộp nhiều khoảng trắng thành 0
       
        for (kieudang k : KDCN.findAll()) {
             String db= k.getTenkieudang().trim().replaceAll("\\s+", "");
            if (input.equalsIgnoreCase(db)) {
                XDialog.alert("Trùng Tên Kiểu Dáng");
                txt_name.setText("");
                return;
            }
        }
        kieudang h = this.getformKieuDang();
        KDCN.create(h);
        XDialog.alert("Thêm Thành Công");
    }

    public void createLoaiDeGiay() {
        if (!XDialog.confirm("Bạn có muốn thêm không")) {
            return;
        }
        
        if (txt_name.getText().trim().isEmpty()) {
            txt_name.requestFocus();
            XDialog.alert("Tên Bị Trống");
            return;
        }
         // biểu thức chính quy
         String regex = "^[\\p{L}\\s]+$";
         if (!txt_name.getText().matches(regex)) {
            XDialog.alert("Tên kiểu dáng phải là chữ và không có kí tự đặc biệt");
            txt_name.setText("");
            return ;
        }
        String input =txt_name.getText().trim().replaceAll("\\s+", "");// replaceAll dùng để gộp nhiều khoảng trắng thành 0
       
        for (loaidegiay k : LDGCN.findAll()) {
             String db= k.getTenloaidegiay().trim().replaceAll("\\s+", "");
            if (input.equalsIgnoreCase(db)) {
                XDialog.alert("Trùng Tên Loại Đế Giày");
                txt_name.setText("");
                return;
            }
        }
        loaidegiay h = this.getformLoaiDeGiay();
        LDGCN.create(h);
        XDialog.alert("Thêm Thành Công");
    }

    public void createLoaiGiay() {
        if (!XDialog.confirm("Bạn có muốn thêm không")) {
            return;
        }
        
        if (txt_name.getText().trim().isEmpty()) {
            txt_name.requestFocus();
            XDialog.alert("Tên Bị Trống");
            return;
        }
         // biểu thức chính quy
         String regex = "^[\\p{L}\\s]+$";
         if (!txt_name.getText().matches(regex)) {
            XDialog.alert("Tên kiểu dáng phải là chữ và không có kí tự đặc biệt");
             txt_name.setText("");
            return ;
        }
        String input =txt_name.getText().trim().replaceAll("\\s+", "");// replaceAll dùng để gộp nhiều khoảng trắng thành 0
       
        for (loaigiay k : LDCN.findAll()) {
              String db= k.getTenloaigiay().trim().replaceAll("\\s+", "");
            if (input.equalsIgnoreCase(db)) {
                XDialog.alert("Trùng Tên Loại Giày");
                txt_name.setText("");
                return;
            }
        }
        loaigiay h = this.getformLOaiGiay();
        LDCN.create(h);
        XDialog.alert("Thêm Thành Công");
    }

    public void createMauSac() {
        if (!XDialog.confirm("Bạn có muốn thêm không")) {
            return;
        }
        
        if (txt_name.getText().trim().isEmpty()) {
            txt_name.requestFocus();
            XDialog.alert("Tên Bị Trống");
            return;
        }
         // biểu thức chính quy
         String regex = "^[\\p{L}\\s]+$";
         if (!txt_name.getText().matches(regex)) {
            XDialog.alert("Tên kiểu dáng phải là chữ và không có kí tự đặc biệt");
             txt_name.setText("");
            return ;
        }
        String input =txt_name.getText().trim().replaceAll("\\s+", "");// replaceAll dùng để gộp nhiều khoảng trắng thành 0
       
        for (mausac k : lstMauSacs) {
              String db= k.getTenmausac().trim().replaceAll("\\s+", "");
            if (input.equalsIgnoreCase(db)) {
                XDialog.alert("Trùng Tên Màu Sắc");
                txt_name.setText("");
                return;
            }
        }
        mausac h = this.getformMauSac();
        MSCN.create(h);
        XDialog.alert("Thêm Thành Công");
    }

    public void createXuatXu() {
        if (!XDialog.confirm("Bạn có muốn thêm không")) {
            return;
        }
        
        if (txt_name.getText().trim().isEmpty()) {
            txt_name.requestFocus();
            XDialog.alert("Tên Bị Trống");
            return;
        }
         // biểu thức chính quy
         String regex = "^[\\p{L}\\s]+$";
         if (!txt_name.getText().matches(regex)) {
            XDialog.alert("Tên kiểu dáng phải là chữ và không có kí tự đặc biệt");
             txt_name.setText("");
            return ;
        }
        String input =txt_name.getText().trim().replaceAll("\\s+", "");// replaceAll dùng để gộp nhiều khoảng trắng thành 0
       
        for (xuatxu k : XXCN.findAll()) {
             String db= k.getTenxuatxu().trim().replaceAll("\\s+", "");
            if (input.equalsIgnoreCase(db)) {
                XDialog.alert("Trùng Tên Xuất Xứ");
                txt_name.setText("");
                return;
            }
        }
        xuatxu h = this.getformXuatXu();
        XXCN.create(h);
        XDialog.alert("Thêm Thành Công");
    }

    public String maXX() {
        String prefix = "XX-";
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder sb = new StringBuilder();

        Random random = new Random();
        for (int i = 0; i < 6; i++) {
            int index1 = random.nextInt(chars.length());
            sb.append(chars.charAt(index1));
        }

        return prefix + sb.toString();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_themthuoctinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_mathuoctinh;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
