/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package shoesvip.ui;

import shoesvip.util.XDialog;
import shoesvip.entity.diachikhachhang;
import shoesvip.dao.impl.diachikhachhangDAOImpl;
import shoesvip.dao.diachikhachhangDAO;

/**
 *
 * @author Ba Nguyen
 */
public class themdiachinhanhJDialog extends javax.swing.JDialog {

    /**
     * Creates new form themdiachinhanhJDialog
     */
   
    public themdiachinhanhJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txt_thêmdiachi.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_thêmdiachi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_diachicuthe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_phuongxa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_quanhuyen = new javax.swing.JTextField();
        txt_tp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_huy = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_thêmdiachi.setBackground(new java.awt.Color(102, 102, 102));
        txt_thêmdiachi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_thêmdiachi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_thêmdiachi.setText("Thêm Địa Chỉ");
        txt_thêmdiachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_thêmdiachiActionPerformed(evt);
            }
        });

        jLabel1.setText("Địa Chỉ Cụ Thể:");

        jLabel2.setText("Phường Xã:");

        jLabel3.setText("Quận Huyện:");

        jLabel4.setText("Tỉnh Thành Phố:");

        btn_huy.setBackground(new java.awt.Color(102, 102, 102));
        btn_huy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_huy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btn_huy.setText("Hủy");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(102, 102, 102));
        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-removebg-preview.png"))); // NOI18N
        btn_add.setText("Thêm");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(txt_thêmdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_huy)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_diachicuthe)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_phuongxa, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_tp, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_quanhuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btn_add)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txt_thêmdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_diachicuthe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_quanhuyen))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_phuongxa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tp))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_huy)
                    .addComponent(btn_add))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_thêmdiachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_thêmdiachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_thêmdiachiActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        if (!XDialog.confirm("Bạn có muốn thêm không")) {
            return;
        }

        diachikhachhang dc = this.getFormDiaChi(); // bạn cần viết thêm hàm này giống getformChatLieu...
        diachikhachhangDAO dcDAO = new diachikhachhangDAOImpl();
        // Kiểm tra rỗng
        if (txt_diachicuthe.getText().trim().isEmpty()
                || txt_phuongxa.getText().trim() == null
                || txt_quanhuyen.getText().trim() == null
                || txt_tp.getText().trim() == null) {
            XDialog.alert("Vui lòng nhập đầy đủ thông tin địa chỉ");
            return;
        }

        // Kiểm tra trùng
        for (diachikhachhang d : dcDAO.findAll()) {
            if (d.getDiachicuthe().equalsIgnoreCase(txt_diachicuthe.getText().trim())
                    && d.getPhuongxa().equalsIgnoreCase((String) txt_phuongxa.getText().trim())
                    && d.getQuanhuyen().equalsIgnoreCase((String) txt_quanhuyen.getText().trim())
                    && d.getTinhthanh().equalsIgnoreCase((String) txt_tp.getText().trim())) {
                XDialog.alert("Địa chỉ đã tồn tại");
                return;
            }
        }

        // Thêm
        dcDAO.add(dc);
    XDialog.alert("Thêm địa chỉ thành công");
    this.diaChiVuaThem = dc; // Gán địa chỉ vừa thêm
    this.submitted = true;
    this.dispose();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_huyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(themdiachinhanhJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(themdiachinhanhJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(themdiachinhanhJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(themdiachinhanhJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                themdiachinhanhJDialog dialog = new themdiachinhanhJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private boolean submitted = false;
    private diachikhachhang diaChiVuaThem;

    public diachikhachhang getDiaChiVuaThem() {
        return diaChiVuaThem;
    }

    public boolean isSubmitted() {
        return submitted;
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
        // ... validate và lưu
        submitted = true;
        this.dispose();
    }

    public void setDiaChiFromString(String diaChiStr) {
        // Ví dụ chuỗi "123 ABC, Phường 5, Quận 10, TP.HCM"
        String[] parts = diaChiStr.split(",");
        if (parts.length >= 4) {
            txt_diachicuthe.setText(parts[0].trim());
            txt_phuongxa.setText(parts[1].trim());
            txt_quanhuyen.setText(parts[2].trim());
            txt_tp.setText(parts[3].trim());
        }
    }

    public diachikhachhang getFormDiaChi() {
        diachikhachhang dc = new diachikhachhang();
        dc.setDiachicuthe(txt_diachicuthe.getText().trim());
        dc.setPhuongxa((String) txt_phuongxa.getText().trim());
        dc.setQuanhuyen((String) txt_quanhuyen.getText().trim());
        dc.setTinhthanh((String) txt_tp.getText().trim());
        return dc;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_huy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_diachicuthe;
    private javax.swing.JTextField txt_phuongxa;
    private javax.swing.JTextField txt_quanhuyen;
    private javax.swing.JTextField txt_thêmdiachi;
    private javax.swing.JTextField txt_tp;
    // End of variables declaration//GEN-END:variables
}
